fix

diff --git a/scripts/nixupd b/scripts/nixupd
--- a/scripts/nixupd
+++ b/scripts/nixupd
@@ -19,9 +19,10 @@ colored() {
 }
 
 handle_error() {
-    msg_if_success="$1"
-    msg_if_failure="$2"
-    if [ "$?" = "0" ]; then 
+    exit_code="$1"
+    msg_if_success="$2"
+    msg_if_failure="$3"
+    if [ "$exit_code" = "0" ]; then 
         colored green "$1"
     else
         colored red "$2" 
@@ -34,14 +35,12 @@ flakedir="${1-}"
 if [ "$flakedir" = "" ]; then
     flakedir="$HOME/src/nix-dotfiles"
 fi
-cd "$flakedir"
-handle_error "" "Failed to cd to flake dir: $flakedir"
+cd "$flakedir" || (colored red "Failed to cd to flake dir: $flakedir"; exit 1)
 
 read -r -p "Update flake? [Y/n]: " update_flake
 if [ "$update_flake" = "Y" ]; then
     colored blue "Updating flake..."
-    nix flake update 
-    handle_error "Flake updated!" "Failed to update flake"
+    handle_error (nix flake update) "Flake updated!" "Failed to update flake"
 fi
 read -r -p "Commit everything? [Y/n]: " commit_everything
 if [ "$commit_everything" = "Y" ]; then
@@ -51,8 +50,7 @@ if [ "$commit_everything" = "Y" ]; then
 fi
 colored blue "Rebuilding..."
 
-nixos-rebuild build --flake .#default
-handle_error "Rebuild successful!" "Failed to rebuild system"
+handle_error (nixos-rebuild build --flake .#default) "Rebuild successful!" "Failed to rebuild system"
 
 nvd diff /run/current-system result
 
@@ -60,8 +58,9 @@ read -r -p "Switch systems? [Y/n]: " switch_systems
 if [ "$switch_systems" = "Y" ]; then
     colored blue "Switching systems..."
     
-    sudo nix-env --profile /nix/var/nix/profiles/system --set ./result && \
-    sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch
+    handle_error \
+        (sudo nix-env --profile /nix/var/nix/profiles/system --set ./result && \
+            sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch)\
+        "System switch successful!" "Failed to switch systems"
 
-    handle_error "System switch successful!" "Failed to switch systems"
 fi
